DELETE http://localhost:8080/events/3/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRvbUJyYWR5IiwiZXhwIjoxNzA1NTMyNTg1LCJ1c2VySUQiOjN9.xZVcQPWodNap79mWUp75LE_SITDvP0J_qtGYh7qm5GQ