PUT http://localhost:8080/changePassword
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlRvbUJyYWR5IiwiZXhwIjoxNzA1NTMyNTg1LCJ1c2VySUQiOjN9.xZVcQPWodNap79mWUp75LE_SITDvP0J_qtGYh7qm5GQ

{
  "email":"TomBrady",
  "password": "dogLover12"
}